version: "3"
services:
  jupyter:
    build: .
    volumes:
      - ./${PROJ}:/kaggle/working/
      - ./kaggle.json:/root/.kaggle/kaggle.json
      - ./input:/kaggle/input
    working_dir: /kaggle/working
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]