version: "3"
services:
  jupyter:
    build: .
    volumes:
      - .:/tmp/working
      - ./kaggle.json:/root/.kaggle/kaggle.json
    working_dir: /tmp/working
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser