FROM gcr.io/kaggle-gpu-images/python:v132

# install torch manually to use local GPU
RUN pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 -f https://download.pytorch.org/whl/torch_stable.html
